### ISSUE TITLE
Spaces in directory name(s) causes failure

### ISSUE THREAD

**Issue by Hekku2** [stjohnjohnson/jenkins-mocha#10]
Issue mainly rises when jenkins has project name with spaces.

```
vagrant@vagrant-ubuntu-trusty-64:~/jenkins mocha$ npm test

> jenkins-mocha@2.4.0 test /home/vagrant/jenkins mocha
> node ./bin/jenkins.js

/bin/sh: 1: /home/vagrant/jenkins: not found
npm ERR! Test failed.  See above for more details.
```

**Comment by stjohnjohnson** [comment]
Oh interesting.  Hmm.

**Comment by stjohnjohnson** [comment]
I think I need to include https://www.npmjs.com/package/shell-escape to resolve this.  Or enclose everything in quotes.

**Comment by Hekku2** [comment]
Tried to fix this in #11.

**Comment by stjohnjohnson** [comment]
Should be resolved, can you double-check if it's working for you?

**Comment by Hekku2** [comment]
Worked for me.
