### ISSUE TITLE
move istanbul to a peer dependancy so we can use newer versions (which support es6)

### ISSUE THREAD

**Issue by halkeye** [stjohnjohnson/jenkins-mocha#22]

**Comment by stjohnjohnson** [comment]
Peer Deps are not recommended from NPM last I heard.  They don't ensure that istanbul exists and it means users need to add another dependency to their package.json.

**Comment by halkeye** [comment]
I don't see that being a problem, but its your package

**Comment by stjohnjohnson** [comment]
I think this can all be resolved when we move to `nyc` instead: https://github.com/stjohnjohnson/jenkins-mocha/pull/24

**Comment by stjohnjohnson** [comment]
Moved to nyc, supports es6
