### ISSUE TITLE
NYC dependency causes tests to fail.

### ISSUE THREAD

**Issue by avik-so** [stjohnjohnson/jenkins-mocha#26]
There is a new version NYC which solves an issue where function.name isn't recognised. See nyc issue here:  https://github.com/istanbuljs/nyc/issues/489
And 
Can you please update your nyc dependency to version 10.1.2?

Thank you.

I tried to [fork the repo ](https://github.com/avik-so/jenkins-mocha)and make the change myself, but when testing I ran into the following error:

node_modules/jenkins-mocha/node_modules/.bin/nyc:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3

npm ERR! Linux 4.2.0-42-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "test_jenkins"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

**Comment by stjohnjohnson** [comment]
Interesting, we're using the `^` notation for our nyc dependency: https://github.com/stjohnjohnson/jenkins-mocha/blob/master/package.json#L31

That should pull in anything that's not a major version difference.  So 10.1.2 should automatically be pulled in.

**Comment by avik-so** [comment]
It does indeed work, I was apparently experiencing this issue even though I was running on a unix VM within windows. https://github.com/gotwarlost/istanbul/issues/677
