### ISSUE TITLE
Dependency to vulnerable version of growl

### ISSUE THREAD

**Issue by mgosui** [stjohnjohnson/jenkins-mocha#31]
Currently jenkins-mocha depends on mocha ^3.0.0, which installs vulnerable version of growl (1.9.2).
https://github.com/stjohnjohnson/jenkins-mocha/blob/master/package.json#L29
 
Upgrading to mocha 4.0.0 or above should fix this, but I’m not sure whether simple upgrade won’t cause any problem.
https://github.com/mochajs/mocha/commit/e39a86748ef57293b3d91c17359369a9b259d533

**Comment by stjohnjohnson** [comment]
Nice.  Okay, I'll give a PR to increase to v4.

**Comment by stjohnjohnson** [comment]
`+ jenkins-mocha@6.0.0`

**Comment by mgosui** [comment]
Thank you for quick response!
