### ISSUE TITLE
add option to disable coverage reporting

### ISSUE THREAD

**Issue by koulmomo** [stjohnjohnson/jenkins-mocha#4]
@stjohnjohnson 

It would be nice if we could pass a flag that would turn off coverage collection/reporting since we can't run mocha independently anymore.

**Comment by stjohnjohnson** [comment]
Cool cool.  Why would you want to turn off coverage and reporting btw?

**Comment by koulmomo** [comment]
I usually have two scripts in my `package.json` `devtest` and `test`.

`devtest` just runs unit-tests and is used by my `precommit-hook` when developing (essentially, make sure tests run and pass, ideally is fast)

`test` runs unit tests and collects coverage info, used by **CI**, ok for it to be slightly slower.

**Comment by arjansingh** [comment]
:+1:  To this idea. Coverage usually ads an order of magnitude to time it takes to run unit tests (`seconds --> minutes`).

The simple solution would just be not to use `istanbul` if there's no coverage directory [`env`](https://github.com/stjohnjohnson/jenkins-mocha/blob/master/lib/jenkins.js#L32) variable.

**Comment by stjohnjohnson** [comment]
@arjansingh I've never seen an order of magnitude difference, but I can understand the concern.

I'd prefer a flag like `--no-coverage` over checking environment variables.  It makes the intention clear.

I'll try to add this in the next few days, but if you want to beat me to the punch with a PR, I would be super grateful! :)

**Comment by stjohnjohnson** [comment]
Available in jenkins-mocha@2.2.0!
