### ISSUE TITLE
Bump Mocha

### ISSUE THREAD

**Issue by brettz9** [stjohnjohnson/jenkins-mocha#42]
Hi,

Getting a vulnerability warning through `jenkins-mocha`'s older Mocha dependency. Mocha until recently was using an older `mkdirp` which was in turn using a [vulnerable `minimist`](https://npmjs.com/advisories/1179). Could you bump your dep. version to the latest Mocha release which, though still targeting a version of `mkdirp` that is deprecated (given `mkdirp`'s 1.x series adding a breaking change to a newer Promise-based API which Mocha is not yet using), is at least pointing to a version without security vulnerabilities?

Thanks!

**Comment by sozakir** [comment]
@stjohnjohnson any update on this ??
mocha has recently fixed minimist vulnerability in 7.1.1 version

**Comment by brettz9** [comment]
Looks like this should now be fixed by #43  so closing. Thanks!
