### ISSUE TITLE
Vulnerability in minimatch version 0.3.4  

### ISSUE THREAD

**Issue by CBsal** [stjohnjohnson/jenkins-mocha#46]
jenkins-mocha has a dependency on mocha ^7.1.1, the latest available version of mocha with major version 7 has a dependency on minimatch version 3.0.4

ReDOS vulnerability has been identified in minimatch 3.0.4 
https://github.com/advisories/GHSA-f8q6-p94x-37v3

Ask is to upgrade mocha to resolve this issue.

**Comment by stjohnjohnson** [comment]
Resolved!
